openapi: 3.0.3

# Informacion general de la API

info:
  title: Catalogo Videojuegos
  description: API para manejar una aplicacion que gestiona catalogos de videojuegos
  version: 1.0.0

# Servidor que es utilizado por la API
servers:
  - url: http://localhost:3000

# Rutas de la API
paths:
  /new/user:
    post:
      summary: Ruta para registrar un nuevo usuario en la base de datos
      requestBody: 
        required: true
        content: 
          application/json: 
            schema: 
              type: object
              properties: 
                nombre:
                  type: string
                pass:
                  type: string
                correo:
                  type: string
                imagen: 
                  type: string
      responses:
        "201":
          description: El usuario fue almacenado con exito en la base de datos
        "403":
          description: Existe un problema con la validacion de credenciales o el correo que se intenta registrar ya se encuentra en la base de datos
        "500":
          description: Ha ocurrido un error interno en el servidor

  /verify:
    post:
      summary: Endpoint para validar credenciales del usuario, iniciar sesión y entregar el token de sesión.
      requestBody: 
        required: true
        content: 
          application/json: 
            schema:
              type: object
              properties: 
                correo:
                  type: string
                pass:
                  type: string
      responses:
        "404": 
          description: Correo o contraseña incorrectos.
        "200": 
          description: El usuario inicio sesion correctamente y se entrego el token.
        "500":
          description: Ha ocurrido un error interno en el servidor.
        "403":
          description: Correo o contraseña incorrectos.

  /validate:
    post:
      summary: Endpoint para validar que el token del usuario es legitimo.
      requestBody: 
        required: true
        content: 
          application/json: 
            schema:
              type: object
              properties: 
                cookie:
                  type: string
                  example: token=token_aqui
                    
      responses:
        "401": 
          description: El token del usuario esta alterado o no es legitimo.
        "200": 
          description: El token del usuario es legitimo.
  
  /add/game:
    post:
      summary: Endpoint para agregar un nuevo juego a la coleccion del usuario.
      requestBody: 
        required: true
        content: 
          application/json: 
            schema: 
              type: object
              properties: 
                token:
                  type: string
                nombre_juego:
                  type: string
                genero:
                  type: string
                plataformas:
                  type: array
                  items: 
                    type: string
                  example: ['xbox','playstation','steam', 'epic games store', 'nes']
                lanzamiento:
                  type: string
                  example: 'YYYY-MM-DD'
                desc:
                  type: string
                imagen:
                  type: string
                  example: https://i.png|webp|jpeg|jpg
                estado:
                  type: string
                  example: deseado | proximamente | adquirido | completado
      responses: 
        "404":
          description: El usuario no tiene una coleccion en la base de datos.
        "500":
          description: Hubo un error por nuestra parte.
        "200":
          description: El juego fue agregado correctamente.

  /edit/game/{id}:
    put:
      parameters: 
        - name: id
          required: true
          in: path
          schema: 
            type: string
      summary: Endpoint para editar un juego existente en la coleccion del usuario.
      requestBody: 
        required: true
        content: 
          application/json: 
            schema: 
              type: object
              properties: 
                token:
                  type: string
                nombre_juego:
                  type: string
                genero:
                  type: string
                plataformas:
                  type: array
                  items: 
                    type: string
                  example: ['xbox','playstation','steam', 'epic games store', 'nes']
                lanzamiento:
                  type: string
                  example: YYYY-MM-DD
                desc: 
                  type: string
                imagen:
                  type: string
                  example: https://i.png|jpg|jpeg|webp
                estado:
                  type: string
                  example: deseado | proximamente | adquirido | completado
      responses: 
        "400":
          description: Los datos enviados no cumplen con la validacion de datos.
        "404":
          description: El usuario no cuenta con una coleccion o el juego que se intenta actualizar no existe.
        "200":
          description: El videojuego ha sido actualizado con exito.
        "500":
          description: Ha ocurrido un error por nuestra parte.

  /games:
    get:
      summary: Endpoint para obtener todos los videojuegos que se muestran en el catalogo.
      responses: 
        "200":
          description: Se entrega al cliente todos los videojuegos almacenados en la base de datos.
        "500":
          description: Hubo un error por parte del servidor.

  /games/detail/{id}:
    get:
      parameters: 
        - name: id
          required: true
          in: path
          schema: 
            type: string
      summary: Endpoint que permite obtener informacion de un videojuego pasando el ID del mismo.
      responses: 
        "404":
          description: No se ha encontrado un videojuego.
        "200":
          description: Se retorna al usuario la informacion del videojuego encontrado.
        "500":
          description: Hubo un error por parte del servidor.

  /games/search/{word}:
    get: 
      parameters: 
        - name: word
          required: true
          in: path
          schema: 
            type: string
      summary: Endpoint que permite encontrar videojuegos por palabra clave.
      responses:
        "200":
          description: Se encontraron coincidencias para la busqueda del usuario.
        "500":
          description: Hubo un error por parte del servidor.
        "404":
          description: No se ha encontrado coincidencias para la busqueda o no se envio nada como query.

  /user/collection/{id}:
    get: 
      parameters: 
        - name: id
          required: true
          in: path
          schema: 
            type: string
      summary: Ruta para obtener todos los videojuegos de la coleccion de un usuario.
      responses: 
        "404":
          description: El usuario no cuenta con una coleccion en la base de datos.
        "200":
          description: Se envio al usuario todos los videojuegos que hacen parte de su coleccion.
        "500":
          description: Hubo un error por parte del servidor.

  /user/collection/search/{word}/{id}:
    get: 
      parameters: 
        - name: word
          required: true
          in: path
          schema: 
            type: string
        - name: id
          required: true
          in: path
          schema: 
            type: string
            example: token del usuario
      summary: Buscar juegos en la coleccion del usuario por medio de una palabra clave.
      responses: 
        "404":
          description: El usuario no cuenta con una coleccion o no se encuentra registrado.
        "200":
          description: Se encontraron videojuegos que coinciden con la busqueda, y entregan al cliente.
        "500":
          description: Hubo un error por parte del servidor.

  /user/collection/details/{id_juego}/{id}:
    get: 
      parameters: 
        - name: id_juego
          required: true
          in: path
          schema: 
            type: string
        - name: id
          required: true
          in: path
          schema: 
            type: string
            example: token del usuario
      responses: 
        "404":
          description: El usuario no cuenta con una coleccion, no esta registrado o el juego que se busca no existe.
        "200":
          description: Se encontro y entrego la informacion del juego buscado al usuario.
        "500":
          description: Hubo un error por parte del servidor.

  /delete/{id}/{token}:
    delete: 
      parameters: 
        - name: id
          required: true
          in: path
          schema: 
            type: string
            example: id del juego a eliminar
        - name: token
          required: true
          in: path
          schema: 
            type: string
      responses: 
        "404":
          description: El juego que se desea eliminar no existe, el usuario no tiene una coleccion o el token es invalido.
        "200":
          description: El juego fue eliminado.
        "500":
          description: Hubo un error por parte del servidor.